apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplica
spec:
  replicas: 2
  selector:
      matchLabels:
        app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: fabricioveronez/web-page:blue
        ports:
        - containerPort: 80 